require "test_helper"

class TestMartSearchProjectUtils < Test::Unit::TestCase
  include MartSearch::ProjectUtils
  public  :get_top_level_project_info, :get_human_orthalog, :get_mice
  
  context "A valid MartSearch Project" do
    setup do
      VCR.insert_cassette( "test_project_utils" )
      @datasources = MartSearch::Controller.instance().datasources
      @project_id  = 35505
    end

    should "have top level information" do
      expected = {
        :marker_symbol    => "Cbx1",
        :mgi_accession_id => "MGI:105369",
        :ensembl_gene_id  => "ENSMUSG00000018666",
        :vega_gene_id     => "OTTMUSG00000001636",
        :ikmc_project     => "EUCOMM",
        :status           => "Mice - Genotype confirmed",
        :mouse_available  => "1",
        :escell_available => "1",
        :vector_available => "1"
      }
      assert_equal( expected, get_top_level_project_info( @datasources, @project_id )[:data][0] )
    end

    should "have the correct human orthalog" do
      expected = { :human_ensembl_gene => "ENSG00000108468" }
      assert_equal( expected, get_human_orthalog( @datasources, "ENSMUSG00000018666" )[:data][0] )
    end

    should "have the expected results" do
      expected = {
        :project_id           => 35505,
        :marker_symbol        => "Cbx1",
        :mgi_accession_id     => "MGI:105369",
        :ensembl_gene_id      => "ENSMUSG00000018666",
        :vega_gene_id         => "OTTMUSG00000001636",
        :ikmc_project         => "EUCOMM",
        :status               => "Mice - Genotype confirmed",
        :mouse_available      => "1",
        :escell_available     => "1",
        :vector_available     => "1",
        :human_ensembl_gene   => "ENSG00000108468",
        :mice                 => [
          {
            :status                        => "Genotype Confirmed",
            :allele_name                   => "Cbx1<sup>tm1a(EUCOMM)Wtsi</sup>",
            :escell_clone                  => "EPD0027_2_B01",
            :emma                          => "1",
            :escell_strain                 => "C57BL/6N",
            :escell_line                   => "JM8.N4 (p10)",
            :mi_centre                     => "WTSI",
            :distribution_centre           => "WTSI",
            :qc_southern_blot              => nil,
            :qc_tv_backbone_assay          => "pass",
            :qc_five_prime_lr_pcr          => "na",
            :qc_loa_qpcr                   => "na",
            :qc_homozygous_loa_sr_pcr      => "pass",
            :qc_neo_count_qpcr             => "pass",
            :qc_lacz_sr_pcr                => "pass",
            :qc_five_prime_cass_integrity  => "pass",
            :qc_neo_sr_pcr                 => "na",
            :qc_mutant_specific_sr_pcr     => "pass",
            :qc_loxp_confirmation          => "pass",
            :qc_three_prime_lr_pcr         => "na",
            :qc_count                      => 0,
            "qc_southern_blot"             => "-",
            "qc_tv_backbone_assay"         => "-",
            "qc_five_prime_lr_pcr"         => "-",
            "qc_loa_qpcr"                  => "-",
            "qc_homozygous_loa_sr_pcr"     => "-",
            "qc_neo_count_qpcr"            => "-",
            "qc_lacz_sr_pcr"               => "-",
            "qc_five_prime_cass_integrity" => "-",
            "qc_neo_sr_pcr"                => "-",
            "qc_mutant_specific_sr_pcr"    => "-",
            "qc_loxp_confirmation"         => "-",
            "qc_three_prime_lr_pcr"        => "-"
          }
        ],
        :intermediate_vectors => [
          {
            :name                                  => "PCS00019_A_B11",
            :design_id   => "39792",
            :design_type => "Conditional (Frameshift)",
            :floxed_exon => "ENSMUSE00000110990"
          }
        ],
        :targeting_vectors    => [
          {
            :name        => "PG00019_A_1_B11",
            :design_id   => "39792",
            :design_type => "Conditional (Frameshift)",
            :cassette    => "L1L2_gt2",
            :backbone    => "L3L4_pZero_kan",
            :floxed_exon => "ENSMUSE00000110990"
          },
          {
            :name        => "PG00019_A_2_B11",
            :design_id   => "39792",
            :design_type => "Conditional (Frameshift)",
            :cassette    => "L1L2_gt2",
            :backbone    => "L3L4_pZero_kan",
            :floxed_exon => "ENSMUSE00000110990"
          },
          {
            :name        => "PG00019_A_3_B11",
            :design_id   => "39792",
            :design_type => "Conditional (Frameshift)",
            :cassette    => "L1L2_gt2",
            :backbone    => "L3L4_pZero_kan",
            :floxed_exon => "ENSMUSE00000110990"
          },
          {
            :name        => "PG00019_A_4_B11",
            :design_id   => "39792",
            :design_type => "Conditional (Frameshift)",
            :cassette    => "L1L2_gt2",
            :backbone    => "L3L4_pZero_kan",
            :floxed_exon => "ENSMUSE00000110990"
          },
          {
            :name        => "PGS00019_A_B11",
            :design_id   => "39792",
            :design_type => "Conditional (Frameshift)",
            :cassette    => "L1L2_gt2",
            :backbone    => "L3L4_pZero_kan",
            :floxed_exon => "ENSMUSE00000110990"
          }
        ],
        :es_cells             => {
          :conditional => {
            :cells       => [
              {
                :name                                  => "EPD0027_2_B01",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "yes",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_A02",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_B03",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_C01",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_C03",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_E01",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_E02",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_F01",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_F02",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_F03",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_A01",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 4,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "fail",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_H01",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 5,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "pass",
                :distribution_qc_three_prime_sr_pcr    => "pass",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_H02",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 5,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "pass",
                :distribution_qc_three_prime_sr_pcr    => "pass",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_H03",
                :allele_symbol_superscript             => "tm1a(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 5,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "pass",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "pass",
                :distribution_qc_three_prime_sr_pcr    => "pass",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              }
            ],
            :allele_img  => "http://www.knockoutmouse.org/targ_rep/alleles/902/allele-image",
            :allele_gb   => "http://www.knockoutmouse.org/targ_rep/alleles/902/escell-clone-genbank-file",
            :design_type => "Conditional (Frameshift)"
          },
          :"targeted non-conditional" => {
            :cells       => [
              {
                :name                                  => "EPD0027_2_A03",
                :allele_symbol_superscript             => "tm1e(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "fail",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_B02",
                :allele_symbol_superscript             => "tm1e(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "fail",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_D01",
                :allele_symbol_superscript             => "tm1e(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "fail",
                :production_qc_three_prime_screen      => "fail",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_D02",
                :allele_symbol_superscript             => "tm1e(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "fail",
                :production_qc_three_prime_screen      => "fail",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_D03",
                :allele_symbol_superscript             => "tm1e(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "fail",
                :production_qc_three_prime_screen      => "fail",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_E03",
                :allele_symbol_superscript             => "tm1e(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "fail",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_G01",
                :allele_symbol_superscript             => "tm1e(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "fail",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_G02",
                :allele_symbol_superscript             => "tm1e(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "fail",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              },
              {
                :name                                  => "EPD0027_2_G03",
                :allele_symbol_superscript             => "tm1e(EUCOMM)Wtsi",
                :parental_cell_line                    => "JM8.N4",
                :targeting_vector                      => "PGS00019_A_B11",
                :mouse?                                => "no",
                :qc_count                              => 3,
                :production_qc_five_prime_screen       => "pass",
                :production_qc_loxp_screen             => "fail",
                :production_qc_three_prime_screen      => "pass",
                :production_qc_loss_of_allele          => "-",
                :production_qc_vector_integrity        => "-",
                :distribution_qc_karyotype_high        => "-",
                :distribution_qc_karyotype_low         => "-",
                :distribution_qc_copy_number           => "-",
                :distribution_qc_five_prime_lr_pcr     => "-",
                :distribution_qc_five_prime_sr_pcr     => "-",
                :distribution_qc_three_prime_sr_pcr    => "-",
                :distribution_qc_thawing               => "-",
                :user_qc_southern_blot                 => "-",
                :user_qc_map_test                      => "-",
                :user_qc_karyotype                     => "-",
                :user_qc_tv_backbone_assay             => "-",
                :user_qc_five_prime_lr_pcr             => "-",
                :user_qc_loss_of_wt_allele             => "-",
                :user_qc_neo_count_qpcr                => "-",
                :user_qc_lacz_sr_pcr                   => "-",
                :user_qc_five_prime_cassette_integrity => "-",
                :user_qc_neo_sr_pcr                    => "-",
                :user_qc_mutant_specific_sr_pcr        => "-",
                :user_qc_loxp_confirmation             => "-",
                :user_qc_three_prime_lr_pcr            => "-"
              }
            ],
            :allele_img  => "http://www.knockoutmouse.org/targ_rep/alleles/903/allele-image",
            :allele_gb   => "http://www.knockoutmouse.org/targ_rep/alleles/903/escell-clone-genbank-file",
            :design_type => "Targeted, Non-Conditional"
          }
        },
        :vector_image         => "http://www.knockoutmouse.org/targ_rep/alleles/903/vector-image",
        :vector_gb            => "http://www.knockoutmouse.org/targ_rep/alleles/903/targeting-vector-genbank-file",
        :stage                => "mice",
        :stage_type           => "normal"
      }
      assert_equal( expected, get_ikmc_project_page_data( @project_id )[:data] )
    end

    context "with no mice" do
      setup do
        @project_id = 42474
      end

      should "not throw any exceptions" do
        assert_nothing_raised do
          get_ikmc_project_page_data( @project_id )
        end
      end
    end

    teardown do
      VCR.eject_cassette
    end
  end
end
