#! /usr/bin/env ruby

$:.unshift( "#{File.expand_path(File.dirname(__FILE__))}/../lib" )
require 'martsearch'

ontology_cache = MartSearch::Controller.instance().ontology_cache
ontologies     = {
  'Mouse Gross Anatomy and Development (EMAP)' => 'EMAP:0',
  'Mouse Adult Gross Anatomy (MA)'             => 'MA:0000001',
  'Mammalian Phenotype (MP)'                   => 'MP:0000001'
}

puts "Preparing the OLS ontology cache..."
ontologies.each do |name,root_term|
  puts " - #{name}"
  ontology_cache.prepare_full_cache(root_term)
end
